Optimize construction_phase_d2a using Joern batch processing

diff --git a/dataset/construction_phase_d2a b/dataset/construction_phase_d2a
--- a/dataset/construction_phase_d2a
+++ b/dataset/construction_phase_d2a
@@ -4,12 +4,18 @@ script=$(readlink -f "$0")
 export script_dir=$(dirname "$script")
 export script_name=$(basename "$script")
 
-export output_dir="$1"
+export output_dir=$(realpath "$1")
 slicing_info_file="$2"
 export bitcode_dir="$3"
 samples_to_proccess="${4:-1000000000}"
 start_from_sample="${5:-1}"
-export joern_script_template="${script_dir}/joern_script_d2a_template"
+export tmp_dir_general="/tmp/construction_phase_d2a"
+joern_script="${tmp_dir_general}/joern_script_d2a"
+extracted_samples_file="${tmp_dir_general}/extracted_samples.csv"
+tmp_csv_file="${tmp_dir_general}/tmp.csv"
+
+# get the real number of processed samples
+all_project_samples_cnt=$(cat ${slicing_info_file} | wc -l)
 
 # colors
 export OK='\033[0;92m'
@@ -18,7 +24,7 @@ export ERROR='\033[0;31m'
 export ENDC='\033[0m'
 
 # function which process a single line in slicing_info_file (single sample)
-process_line() {
+create_cpgbin() {
     rc=$1
     bug_id=$2
 		entry_function=$3
@@ -30,33 +36,22 @@ process_line() {
 		# for storing intermediate files
 		tmp_dir="/tmp/construction_phase_d2a_${$}" # unique dir name (using PID)
 		bc_sliced="${tmp_dir}/sliced.bc"
-		cpg_bin="${tmp_dir}/sliced.cpg.bin.zip"
+		cpg_bin="${tmp_dir_general}/${bug_id}.cpg.bin.zip"
 		joern_cpg_bin="${tmp_dir}/workspace/sliced.cpg.bin.zip/cpg.bin"
-		joern_script="${tmp_dir}/joern_script_d2a"
 		bc_combined="${bitcode_dir}/${bug_id}.bc"
-		sample_dir="${output_dir}/${bug_id}"
 
 		if [ ! -e "${bc_combined}" ]; then
-			# samples without bitcode are skipped completely (they don't count as failed
-			# nor successful)
+			# samples without bitcode are skipped (they coun as unsuccessfull)
 			printf "${WARNING}WARNING${ENDC}: ${script_name}: sample '${bug_id}' doesn't have bitcode!\n"
 			exit 0
-		fi
-
-		# skip the sample if its dir already exists
-		if [ -d "${sample_dir}" ]; then
-      exit 0
 		fi
 
 		# create tmp dir
 		mkdir -p ${tmp_dir}
 
-		# create joern script from its template
-		sed "s/PID/${$}/" "${joern_script_template}" > "${joern_script}"
-
 		# slice the combined LLVM bitcode according to extracted slicing criteria
 		# variables already contain required '&' sign
-		timeout 5s llvm-slicer --entry=${entry_function} --sc="${file}#${fun}#${line}#${variable}" -o=${bc_sliced} ${bc_combined} > /dev/null 2> ${tmp_dir}/llvm_slicer_stderr.txt
+		timeout 3s llvm-slicer --entry=${entry_function} --sc="${file}#${fun}#${line}#${variable}" -o=${bc_sliced} ${bc_combined} > /dev/null 2> ${tmp_dir}/llvm_slicer_stderr.txt
 
 		# check if llvm-slicer timed-out, there are 2 reason for that:
 		# 	1) llvm-slicer got stuck
@@ -85,97 +80,100 @@ process_line() {
 			# llvm-slicer coudn't match extracted slicing criteria to bitcode (this is not copy-paste error)
 			printf "${WARNING}WARNING${ENDC}: ${script_name}: skipping bug ${bug_id} because llvm2cpg failed to generate CPG!\n"
 			rm -rf ${tmp_dir}
+      rm -rf ${cpg_bin} # if there was an error remove the result (just to be sure)
 			exit 0
 		fi
-
-		# we need to switch to tmp, because of joern
-		cd ${tmp_dir}
-
-		# joern transforms generated CPG to CSV in Neo4j format
-		# joern creates it's workspace in current dir --> tmp dir
-		joern --script ${joern_script} > /dev/null 2>&1
-
-		# check if joern succeeded
-		# joern stores copy of imported CPG as workspace/sliced.cpg.bin.zip/cpg.bin
-		if [ ! -f "${joern_cpg_bin}" ]; then
-			# joern failed to import CPG generated by llvm2cpg e.g. the CPG file is missing
-			# but when it is there, the cpg.bin is still created (although it may be faulty)
-			printf "${WARNING}WARNING${ENDC}: ${script_name}: skipping bug ${bug_id} because Joern failed to create internal representation of given CPG!\n"
-			rm -rf ${tmp_dir}
-			exit 0
-		fi
-
-		# export Joern's CPG to CSV
-		joern-export --repr all --format neo4jcsv ${joern_cpg_bin} > /dev/null 2>&1
-
-		# check if joern-export succeeded
-		if [ $? -ne 0 ]
-		then
-			# joern-export failed probably due to the faulty ${joern_cpg_bin} which
-			# was caused by joern's importing which failed half-way
-			printf "${WARNING}WARNING${ENDC}: ${script_name}: skipping bug ${bug_id} because joern-export failed to create Neo4j CSV (Joern probably failed to import CPG)!\n"
-			rm -rf ${tmp_dir}
-			exit 0
-		fi
-
-		# switch back to script dir
-		cd ${script_dir}
-
-		# prepare output sample dir (in the first iteration this will also create $(output_dir))
-		mkdir -p ${sample_dir}
-
-		# move all the bug-specific CSV files into it's directory
-		# AST
-		mv ${tmp_dir}/out/edges_AST_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/edges_CONDITION_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_AST_NODE_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_BLOCK_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_CALL_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_CALL_REPR_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_CONTROL_STRUCTURE_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_EXPRESSION_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_FIELD_IDENTIFIER_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_IDENTIFIER_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_JUMP_LABEL_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_JUMP_TARGET_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_LITERAL_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_LOCAL_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_METHOD_REF_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_MODIFIER_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_RETURN_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_TYPE_REF_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_UNKNOWN_* ${sample_dir} 2> /dev/null
-
-		# CallGraph - might be useful
-		mv ${tmp_dir}/out/edges_ARGUMENT_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/edges_CALL_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/edges_RECEIVER_* ${sample_dir} 2> /dev/null
-
-		# CFG
-		mv ${tmp_dir}/out/edges_CFG_* ${sample_dir} 2> /dev/null
-		mv ${tmp_dir}/out/nodes_CFG_NODE_* ${sample_dir} 2> /dev/null # just in case
-
-		# PDG
-		mv ${tmp_dir}/out/edges_CDG_* ${sample_dir} 2> /dev/null
-
-		# Reaching def - might be useful
-		mv ${tmp_dir}/out/edges_REACHING_DEF_* ${sample_dir} 2> /dev/null
-
-		# remove tmp dir
-		rm -rf ${tmp_dir}
-
-		# success
-		printf "${OK}SUCCESS${ENDC}: ${script_name}: CPG for bug ${bug_id} was successfully constructed!\n"
 }
 
-# export function so its visible in newly started subshells in parallel command
-export -f process_line
+# function which process a single line in slicing_info_file (single sample)
+cpgbin_to_csv() {
+    bug_id=$1
+    joern_cpg_bin="${tmp_dir_general}/workspace/${bug_id}.cpg.bin.zip/cpg.bin"
+
+    # check if joern succeeded
+    # joern stores copy of imported CPG as workspace/${bug_id}.cpg.bin.zip/cpg.bin
+    if [ ! -f "${joern_cpg_bin}" ]; then
+      # joern failed to import CPG generated by llvm2cpg e.g. the CPG file is missing
+      # but when it is there, the cpg.bin is still created (although it may be faulty)
+      printf "${WARNING}WARNING${ENDC}: ${script_name}: skipping bug ${bug_id} because Joern failed to create internal representation of given CPG!\n"
+      exit 0
+    fi
+
+    # export Joern's CPG to CSV
+    joern-export --repr all --format neo4jcsv -o "${output_dir}/${bug_id}" ${joern_cpg_bin} > /dev/null 2>&1
+
+    # check if joern-export succeeded
+    if [ $? -ne 0 ]
+    then
+      # joern-export failed probably due to the faulty ${joern_cpg_bin} which
+      # was caused by joern's importing which failed half-way
+      printf "${WARNING}WARNING${ENDC}: ${script_name}: skipping bug ${bug_id} because joern-export failed to create Neo4j CSV (Joern probably failed to import CPG)!\n"
+      rm -rf ${tmp_dir}
+      exit 0
+    fi
+
+    # remove subdir in workspace - it wont needed in future and we save some space, since we are creating new CPGs on disk
+    rm -rf "${tmp_dir_general}/workspace/${bug_id}.cpg.bin.zip/"
+
+    # success
+    printf "${OK}SUCCESS${ENDC}: ${script_name}: CPG for bug ${bug_id} was successfully constructed!\n"
+  }
+
+# export functions so they are visible in newly started subshells in parallel command
+export -f create_cpgbin
+export -f cpgbin_to_csv
+
+# recreate tmp dir
+rm -rf ${tmp_dir_general} && mkdir ${tmp_dir_general}
+
+# extract only required samples to separate file
+head -n ${samples_to_proccess} ${slicing_info_file} | tail -n +${start_from_sample} > ${extracted_samples_file}
+
+# filter out samples with already existing CPGs
+while IFS=, read -r rc bug_id rest; do
+  # skip the sample if its dir already exists
+  if [ -d "${output_dir}/${bug_id}" ]; then
+    continue
+  fi
+  echo "${rc},${bug_id},${rest}"
+done < ${extracted_samples_file} > ${tmp_csv_file}
+
+# save it back to the original file
+mv ${tmp_csv_file} ${extracted_samples_file}
 
 # for each bug report (slicing criteria record)
-head -n ${samples_to_proccess} ${slicing_info_file} | tail -n +${start_from_sample} | parallel --colsep ',' process_line {1} {2} {3} {4} {5} {6} {7}
+cat ${extracted_samples_file} | parallel --colsep ',' create_cpgbin {1} {2} {3} {4} {5} {6} {7}
 
-# get the real number of processed samples
-all_project_samples_cnt=$(cat ${slicing_info_file} | wc -l)
+# filter out samples without cpg.bin.zip
+while IFS=, read -r rc bug_id rest; do
+  # skip the sample if the cpg.bin.zip is missing
+  if [ ! -f "${tmp_dir_general}/${bug_id}.cpg.bin.zip" ]; then
+    continue
+  fi
+  echo "${rc},${bug_id},${rest}"
+done < ${extracted_samples_file} > ${tmp_csv_file}
+
+# save it back to the original file
+mv ${tmp_csv_file} ${extracted_samples_file}
+
+# generate joern_script
+while IFS=, read -r rc bug_id rest; do
+  echo "importCpg(\"/tmp/construction_phase_d2a/${bug_id}.cpg.bin.zip\")"
+done < ${extracted_samples_file} > ${joern_script}
+echo "save" >> ${joern_script}
+
+# we need to switch to tmp, because of joern
+cd ${tmp_dir_general}
+
+# joern transforms generated CPG to CSV in Neo4j format
+# joern creates it's workspace in current dir --> tmp dir general
+joern --script ${joern_script} > /dev/null 2>&1
+
+# prepare output dir
+mkdir -p ${output_dir} 2> /dev/null
+
+# run joern-export in parallel
+cat ${extracted_samples_file} | parallel --colsep ',' cpgbin_to_csv {2}
 
 if [ "${samples_to_proccess}" -lt "${all_project_samples_cnt}" ]; then
     samples_to_proccess=${samples_to_proccess}
